server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
  endpoint:
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    org:
      springframework:
        web: DEBUG